dubbo:
  application:
    name: dubbo-demo-develop-provider
  provider:
    token: false
  registry:
    address: nacos://${nacos.address:localhost}:8848?username=nacos&password=nacos
  protocol:
    name: dubbo
    port: 20881